# Generated by Django 5.2.1 on 2025-06-18 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('manguoidung', models.AutoField(db_column='maNguoiDung', primary_key=True, serialize=False)),
                ('hoten', models.CharField(db_column='hoTen', max_length=50)),
                ('sodienthoai', models.CharField(db_column='soDienThoai', max_length=20, unique=True)),
                ('password', models.CharField(db_column='matKhau', max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(db_column='ngayTao')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NguoiDung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ca',
            fields=[
                ('maca', models.AutoField(db_column='maCa', primary_key=True, serialize=False)),
                ('gioxuatphat', models.TimeField(db_column='gioXuatPhat')),
                ('ngayxuatphat', models.DateField(db_column='ngayXuatPhat')),
            ],
            options={
                'db_table': 'Ca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietca',
            fields=[
                ('machitietca', models.AutoField(db_column='maChiTietCa', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ChiTietCa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietdatxe',
            fields=[
                ('machitiet', models.AutoField(db_column='maChiTiet', primary_key=True, serialize=False)),
                ('tenkhach', models.CharField(db_column='tenKhach', max_length=50)),
                ('sodienthoaikhach', models.CharField(db_column='soDienThoaiKhach', max_length=20)),
                ('trangthai', models.CharField(db_column='trangThai', max_length=50)),
                ('ghichu', models.TextField(blank=True, db_column='ghiChu', null=True)),
                ('soghe', models.IntegerField(db_column='soGhe', default=1)),
            ],
            options={
                'db_table': 'ChiTietDatXe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datxe',
            fields=[
                ('madatxe', models.AutoField(db_column='maDatXe', primary_key=True, serialize=False)),
                ('thoigiandat', models.DateTimeField(auto_now_add=True, db_column='thoiGianDat', null=True)),
                ('trangthai', models.CharField(db_column='trangThai', max_length=50)),
                ('ghichu', models.TextField(blank=True, db_column='ghiChu', null=True)),
                ('soghe', models.IntegerField(db_column='soGhe', default=1)),
            ],
            options={
                'db_table': 'DatXe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diadiem',
            fields=[
                ('madiadiem', models.AutoField(db_column='maDiaDiem', primary_key=True, serialize=False)),
                ('tendiadiem', models.CharField(db_column='tenDiaDiem', max_length=100)),
                ('vido', models.FloatField(db_column='viDo')),
                ('kinhdo', models.FloatField(db_column='kinhDo')),
            ],
            options={
                'db_table': 'DiaDiem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huyen',
            fields=[
                ('mahuyen', models.AutoField(db_column='maHuyen', primary_key=True, serialize=False)),
                ('tenhuyen', models.CharField(db_column='tenHuyen', max_length=100)),
            ],
            options={
                'db_table': 'Huyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tuyenduong',
            fields=[
                ('matuyenduong', models.AutoField(db_column='maTuyenDuong', primary_key=True, serialize=False)),
                ('giacuoc', models.DecimalField(db_column='giaCuoc', decimal_places=2, max_digits=10)),
                ('huongchay', models.IntegerField(db_column='huongChay', default=1, help_text='1: Đà Nẵng đi Tam Kỳ, 2: Tam Kỳ đi Đà Nẵng')),
            ],
            options={
                'db_table': 'TuyenDuong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vaitro',
            fields=[
                ('mavaitro', models.IntegerField(db_column='maVaiTro', primary_key=True, serialize=False)),
                ('tenvaitro', models.CharField(db_column='tenVaiTro', max_length=15)),
            ],
            options={
                'db_table': 'VaiTro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('maxe', models.AutoField(db_column='maXe', primary_key=True, serialize=False)),
                ('biensoxe', models.CharField(db_column='bienSoXe', max_length=20)),
                ('loaixe', models.CharField(blank=True, db_column='loaiXe', max_length=50, null=True)),
                ('sochongoi', models.IntegerField(db_column='soChoNgoi')),
            ],
            options={
                'db_table': 'Xe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlacklistedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('manhanvien', models.OneToOneField(db_column='maNhanVien', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ngayvaolam', models.DateField(db_column='ngayVaoLam')),
                ('cccd', models.CharField(blank=True, max_length=20, null=True)),
                ('trangthai', models.IntegerField(blank=True, db_column='trangThai', null=True)),
            ],
            options={
                'db_table': 'NhanVien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taixe',
            fields=[
                ('mataixe', models.OneToOneField(db_column='maTaiXe', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cccd', models.CharField(blank=True, max_length=20, null=True)),
                ('trangthai', models.IntegerField(blank=True, db_column='trangThai', null=True)),
            ],
            options={
                'db_table': 'TaiXe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Danhgia',
            fields=[
                ('madatxe', models.OneToOneField(db_column='maDatXe', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='datxe_backend.datxe')),
                ('diemso', models.IntegerField(db_column='diemSo')),
                ('binhluan', models.TextField(blank=True, db_column='binhLuan', null=True)),
                ('ngaydanhgia', models.DateField(db_column='ngayDanhGia')),
            ],
            options={
                'db_table': 'DanhGia',
                'managed': False,
            },
        ),
    ]
