# Generated by Django 5.2.1 on 2025-06-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datxe_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diadiem',
            options={'managed': False, 'verbose_name': 'Địa điểm', 'verbose_name_plural': 'Quản lý Địa điểm'},
        ),
        migrations.AlterModelOptions(
            name='huyen',
            options={'managed': False, 'verbose_name': 'Huyện', 'verbose_name_plural': 'Quản lý Huyện'},
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'managed': False, 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Quản lý Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='vaitro',
            options={'managed': False, 'verbose_name': 'Vai trò', 'verbose_name_plural': 'Quản lý Vai trò'},
        ),
    ]
